version: '3.7'

services:
   app:
      image: tazodocker
      depends_on:
         - bd
      environment:
         SECRET_KEY: ${SECRET_KEY}
         BD_NAME: ${BD_NAME}
         BD_USER: ${BD_USER}
         BD_PASSWORD: ${BD_PASSWORD}
         BD_HOST: ${BD_HOST}
         BD_PORT: ${BD_PORT}
         RECAPTCHA_PRIVATE_KEY: ${RECAPTCHA_PRIVATE_KEY}
         TOKEN_BOT: ${TOKEN_BOT}
         CHAT_ID: ${CHAT_ID}
         SSH_PUBLIC: ${SSH_PUBLIC}
         SSH_PRIVATE: ${SSH_PRIVATE}
         FINGERPRINT: ${FINGERPRINT}
         CLAVE_OF_KEY: ${CLAVE_OF_KEY}
      volumes:
        - ./Service-management-system:/code
      deploy:
         resources:
            limits:
               cpus: "3"
               memory: "1024M"

   bd:
      image: mariadb
      restart: always
      environment:
        MYSQL_USER: ${BD_USER}
        MYSQL_PASSWORD: ${BD_PASSWORD}
        MYSQL_DATABASE: ${BD_NAME}
        MYSQL_ROOT_PASSWORD: ${BD_ROOT}
      volumes:
         - ./data:/var/lib/mysql
      deploy:
         resources:
            limits:
               cpus: "3"
               memory: "1024M"

   nginx:
      image: nginx
      restart: always
      ports:
        - 80:80
        - 443:443
      volumes:
        - ./nginx:/etc/nginx/conf.d
        - ./Service-management-system/services_management_system/static/:/static
        - ./certificados:/certs
        - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      deploy:
         resources:
            limits:
               cpus: "3"
               memory: "1024M"
