name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Force embedded JRE
        run: echo "sonar.scanner.enableAutodetect=false" >> $RUNNER_TEMP/sonar-scanner-cli-7.1.0.4889-Linux-X64/conf/sonar-scanner.properties

      - uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
